acme_api:
    resource: "@AcmeApiBundle/Resources/config/routing.yml"

app:
    resource: @AppBundle/Controller/
    type:     annotation


# Configure FOSOAuthServerBundle Routing
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"